=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/blockOut.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="window" type="windowType"/>
    <xs:element name="layout" type="layoutType"/>

    <xs:complexType name="windowType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:attribute name="inherit"  type="xs:string"/>
        <xs:attribute name="size"     type="xs:string"/>
        <xs:attribute name="width"    type="xs:string"/>
        <xs:attribute name="height"   type="xs:string"/>
        <xs:attribute name="lightbox" type="xs:boolean"/>
        <xs:attribute name="pause"    type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="layoutType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xs:complexType>

    <!-- Pane basic attributes -->
    <xs:complexType name="paneType">
        <xs:attribute name="id"      type="xs:string"/>

        <xs:attribute name="align"   type="xs:string"/>
        <xs:attribute name="size"    type="xs:string"/>
        <xs:attribute name="width"   type="xs:string"/>
        <xs:attribute name="height"  type="xs:string"/>
        <xs:attribute name="pos"     type="xs:string"/>
        <xs:attribute name="x"       type="xs:string"/>
        <xs:attribute name="y"       type="xs:string"/>

        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="enabled" type="xs:boolean"/>

        <xs:attribute name="style"   type="xs:string"/>
    </xs:complexType>

    <!-- View basic attributes and contents -->
    <xs:complexType name="viewType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Master group for all panes that can be used -->
    <xs:group name="paneContainerGroup">
        <xs:choice>
            <xs:element name="layout"       type="layoutElementType"/>
            <xs:element name="view"         type="viewType"/>
            <xs:element name="group"        type="groupType"/>
            <!-- xs:element name="scrollgroup"  type="scrollGroupType"/ -->
            <xs:element name="list"         type="listType"/>
            <xs:element name="button"       type="buttonType"/>
            <xs:element name="buttonimage"  type="buttonImageType"/>
            <xs:element name="label"        type="labelType"/>
            <xs:element name="input"        type="inputType"/>
            <xs:element name="image"        type="imageType"/>
            <xs:element name="box"          type="boxType"/>
            <xs:element name="itemicon"     type="itemIconType"/>
            <xs:element name="switch"       type="switchType"/>
        </xs:choice>
    </xs:group>

    <!-- <layout> -->
    <xs:complexType name="layoutElementType">
        <xs:attribute name="source" use="required"/>
    </xs:complexType>

    <!-- <group> -->
    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="spacing" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <switch> -->
    <xs:complexType name="switchType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="default" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <box> -->
    <xs:complexType name="boxType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="linewidth" type="xs:decimal"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <list> -->
    <xs:complexType name="listType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <button> -->
    <xs:complexType name="buttonType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="label"      type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <label> -->
    <xs:complexType name="labelType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="label"      type="xs:string"/>
                <xs:attribute name="textscale"  type="xs:string"/>
                <xs:attribute name="textalign"  type="xs:string"/>
                <xs:attribute name="color"      type="xs:string"/>
                <xs:attribute name="hovercolor" type="xs:string"/>
                <xs:attribute name="shadow"     type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <itemicon> -->
    <xs:complexType name="itemIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="item" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <buttonimage> -->
    <xs:complexType name="buttonImageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <!-- Image and Highlight -->
                <xs:attribute name="source"          type="xs:string" use="required"/>
                <xs:attribute name="imageoffset"     type="xs:string"/>
                <xs:attribute name="imagesize"       type="xs:string"/>
                <xs:attribute name="highlight"       type="xs:string"/>
                <xs:attribute name="highlightoffset" type="xs:string"/>
                <xs:attribute name="highlightsize"   type="xs:string"/>
                <!-- Label (optional) -->
                <xs:attribute name="label"      type="xs:string"/>
                <xs:attribute name="textscale"       type="xs:string"/>
                <xs:attribute name="textalign"       type="xs:string"/>
                <xs:attribute name="textoffset"      type="xs:string"/>
                <xs:attribute name="textcolor"       type="xs:string"/>
                <xs:attribute name="texthovercolor"  type="xs:string"/>
                <xs:attribute name="textdisabledcolor" type="xs:string"/>
                <xs:attribute name="shadow"          type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <image> -->
    <xs:complexType name="imageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="imageoffset" type="xs:string"/>
                <xs:attribute name="imagesize" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <input> -->
    <xs:complexType name="inputType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="text"          type="xs:string"/>
                <xs:attribute name="maxlength"     type="xs:integer"/>
                <xs:attribute name="color"         type="xs:string"/>
                <xs:attribute name="colordisabled" type="xs:string"/>
                <xs:attribute name="shadow"        type="xs:boolean"/>
                <xs:attribute name="tab"           type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/townhall/windowtownhallhirecitizen.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" pause="true"
        lightbox="true"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <label size="200 11" pos="100 50" textalign="TOP_MIDDLE" color="white"
           label="$(com.minecolonies.coremod.gui.townHall.hirecitizen1)"/>
    <label size="200 11" pos="100 61" textalign="TOP_MIDDLE" color="white"
           label="$(com.minecolonies.coremod.gui.townHall.hirecitizen2)"/>
    <label size="200 11" pos="100 72" textalign="TOP_MIDDLE" color="white"
           label="$(com.minecolonies.coremod.gui.townHall.hirecitizen3)"/>
    <box size="163 100" linewidth="2" pos="127 87">
        <buttonimage label="16x" textcolor="black" id="hiretopleft" size="80 48" pos="0 0" maxlength="300"
                     source="minecolonies:textures/gui/citizen/colonist_request_button.png" imagesize="80 48"
                     disabled="minecolonies:textures/gui/citizen/colonist_request_button_dark.png" disabledsize="80 48"
                     highlight="minecolonies:textures/gui/citizen/colonist_request_button_light.png" highlightsize="80 48"
        />
        <itemicon id="hiretoplefticon" size="30 30" pos="50 9"/>


        <buttonimage id="hiretopright" textcolor="black" size="80 48" pos="83 0" maxlength="300"
                     source="minecolonies:textures/gui/citizen/colonist_request_button.png" imagesize="80 48"
                     disabled="minecolonies:textures/gui/citizen/colonist_request_button_dark.png" disabledsize="80 48"
                     highlight="minecolonies:textures/gui/citizen/colonist_request_button_light.png" highlightsize="80 48"
        />
        <itemicon id="hiretoprighticon" size="30 30" pos="133 9"/>


        <buttonimage id="hirebottomleft" textcolor="black" size="80 48" pos="0 51" maxlength="300"
                     source="minecolonies:textures/gui/citizen/colonist_request_button.png" imagesize="80 48"
                     disabled="minecolonies:textures/gui/citizen/colonist_request_button_dark.png" disabledsize="80 48"
                     highlight="minecolonies:textures/gui/citizen/colonist_request_button_light.png" highlightsize="80 48"
        />
        <itemicon id="hirebottomlefticon" size="30 30" pos="50 60"/>


        <buttonimage id="hirebottomright" textcolor="black" size="80 48" pos="83 51" maxlength="300"
                     source="minecolonies:textures/gui/citizen/colonist_request_button.png" imagesize="80 48"
                     disabled="minecolonies:textures/gui/citizen/colonist_request_button_dark.png" disabledsize="80 48"
                     highlight="minecolonies:textures/gui/citizen/colonist_request_button_light.png" highlightsize="80 48"
        />
        <itemicon id="hirebottomrighticon" size="30 30" pos="133 60"/>

    </box>
    <button id="done" size="200 20" pos="110 200" label="$(gui.done)"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowlistrecipes.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" pause="true"
        lightbox="true"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <label size="100% 11" pos="0 50" textalign="TOP_MIDDLE" color="white" label="$(com.minecolonies.coremod.gui.workerHuts.listRecipes)"/>
    <list id="recipes" size="70% 120" pos="60 70" align="TOP_MIDDLE">
        <view size="70% 50">
            <itemicon id="output" size="16 16" pos="80 5"/>
            <box id="2x2" size="100% 30" linewidth="2">
                <itemicon id="resource1" size="16 16" pos="20 1"/>
                <itemicon id="resource2" size="16 16" pos="20 15"/>
                <itemicon id="resource3" size="16 16" pos="34 15"/>
                <itemicon id="resource4" size="16 16" pos="34 1"/>
            </box>
            <box id="3x3" size="100% 50" linewidth="2" visible="false">
                <itemicon id="res1" size="16 16" pos="20 1"/>
                <itemicon id="res2" size="16 16" pos="34 1"/>
                <itemicon id="res3" size="16 16" pos="48 1"/>

                <itemicon id="res4" size="16 16" pos="20 15"/>
                <itemicon id="res5" size="16 16" pos="34 15"/>
                <itemicon id="res6" size="16 16" pos="48 15"/>

                <itemicon id="res7" size="16 16" pos="20 29"/>
                <itemicon id="res8" size="16 16" pos="34 29"/>
                <itemicon id="res9" size="16 16" pos="48 29"/>
            </box>
            <button id="up" size="15 15" label="↥" pos="0 0"/>
            <button id="down" size="15 15" label="↧" pos="0 15"/>
            <button id="remove" size="45 15" pos="125 3" label="$(com.minecolonies.coremod.gui.recipe.remove)"/>
        </view>
    </list>
    <button id="cancel" size="200 20" pos="110 194" label="$(gui.cancel)"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutplantation.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="crusherSettings" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label size="130 11" pos="30 14" textalign="MIDDLE" color="black"
                   label="$(com.minecolonies.coremod.gui.workerhuts.crusherSettings):"/>

            <label id="hint" size="86 17" pos="50 40" textalign="MIDDLE" color="black"
                   label="$(com.minecolonies.coremod.gui.workerhuts.plantation.to_plant)" />
            <buttonimage id="block" size="86 17" pos="50 60" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"/>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutwarehouse.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactionsmin.xml"/>
        </view>
        <view id="resourceActions" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label size="130 11" pos="30 14" textalign="MIDDLE" color="black"
                   label="$(com.minecolonies.coremod.gui.warehouse.upgrade)"/>
            <box size="164 30" linewidth="2" pos="13 29">
                <itemicon id="resourceIcon" size="16 16" pos="1 1"/>
                <label id="resourceName" size="125 9" pos="18 2" color="black"/>
                <button id="resourceAdd" size="16 16" label="â†¥" pos="145 2"/>
                <label id="resourceMissing" size="65 9" pos="2 20" textalign="MIDDLE" color="black"/>
                <label id="resourceAvailableNeeded" size="65 9" pos="67 20" textalign="MIDDLE" color="black"/>
                <label id="upgradeProgress" size="40 9" pos="132 20" color="black"/>

                <label id="resourceId" size="1 1" pos="100 100"/>
                <label id="resourceQuantity" size="1 1" pos="100 100"/>
            </box>
            <buttonimage id="sort" size="86 17" pos="50 70" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                         disabled="minecolonies:textures/gui/builderhut/builder_button_medium_large_disabled.png"
                         label="$(com.minecolonies.coremod.gui.warehouse.sort)"/>
        </view>
        <view>
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label size="130 11" pos="30 14" textalign="MIDDLE" color="black"
                   label="$(com.minecolonies.coremod.gui.warehouse.stock)"/>
            <list id="resources" size="170 100" pos="13 50">
                <box size="100% 17" linewidth="2">
                    <itemicon id="resourceIcon" size="17 17" pos="0 0"/>
                    <label id="resourceName" size="90 12" pos="20 1" color="black"/>
                    <label id="resourceQty" size="12 12" pos="115 1" color="black"/>

                    <buttonimage label="X" id="removeStock" pos="130 1" size="29 15"
                                 source="minecolonies:textures/gui/builderhut/builder_button_very_small.png" textcolor="red"/>
                </box>
            </list>
            <buttonimage id="addStock" size="86 17" pos="50 160" textcolor="black"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png"
                         label="$(com.minecolonies.coremod.gui.warehouse.add)"/>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowfilterablelist.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="pageItems" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label id="desc" size="130 11" pos="30 14" color="black" textalign="MIDDLE"/>
            <input id="input" size="150 18" pos="20 30" maxlength="25"/>

            <list id="resources" size="164 136" pos="13 50">
                <box size="100% 17" linewidth="2">
                    <itemicon id="resourceIcon" size="17 17" pos="0 0"/>
                    <label id="resourceName" size="100 12" pos="20 1" color="white"/>
                    <buttonimage label="$(com.minecolonies.coremod.gui.workerHuts.retrieveOn)" id="switch" pos="120 1" size="29 15"
                                 source="minecolonies:textures/gui/builderhut/builder_button_very_small.png" textcolor="black"/>
                </box>
            </list>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowBuildTool.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="420 240" pause="true"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">

    <button id="previousBuildingType" size="15 15" pos="0 0" label="&lt;"/>
    <dropdown id="buildingType" size="114 15" pos="13 0" dropDownSize="140 75">
        <view size="100% 15">
            <label id="id" size="100% 100%" label="" pos="0 0"/>
            <button id="button" size="100% 100%" label="" pos="0 0"/>
        </view>
    </dropdown>
    <button id="nextBuildingType" size="15 15" pos="125 0" label="&gt;"/>

    <button id="previousStyle" size="15 15" pos="140 0" label="&lt;"/>
    <dropdown id="style" size="114 15" pos="153 0" maxContentHeight="75" dropDownSize="140 75">
        <view size="100% 15">
            <label id="id" size="100% 100%" label="" pos="0 0"/>
            <button id="button" size="100% 100%" label="" pos="0 0"/>
        </view>
    </dropdown>
    <button id="nextStyle" size="15 15" pos="265 0" label="&gt;"/>

    <button id="previousSchematic" size="15 15" pos="280 0" label="&lt;"/>
    <dropdown id="schematic" size="114 15" pos="293 0" maxContentHeight="75" dropDownSize="140 75">
        <view size="100% 15">
            <label id="id" size="100% 100%" label="" pos="0 0"/>
            <button id="button" size="100% 100%" label="" pos="0 0"/>
        </view>
    </dropdown>
    <button id="nextSchematic" size="15 15" pos="405 0" label="&gt;"/>

    <button id="rename" size="114 15" pos="293 20" label="Rename" visible="false"/>
    <button id="delete" size="114 15" pos="293 40" label="Delete" visible="false"/>

    <view size="60 112" pos="180 120">
        <buttonimage id="rotateLeft"  source="minecolonies:textures/gui/rotateLeft-20px.png"  size="20" pos="0 0"/>
        <buttonimage id="forward"     source="minecolonies:textures/gui/up-20px.png"          size="20" pos="20 0"/>
        <buttonimage id="rotateRight" source="minecolonies:textures/gui/rotateRight-20px.png" size="20" pos="40 0"/>
        <buttonimage id="left"        source="minecolonies:textures/gui/left-20px.png"        size="20" pos="0 20"/>
        <buttonimage id="mirror"      source="minecolonies:textures/gui/mirror-20px.png"      size="20" pos="20 20"/>
        <buttonimage id="right"       source="minecolonies:textures/gui/right-20px.png"       size="20" pos="40 20"/>
        <buttonimage id="down"        source="minecolonies:textures/gui/minus-20px.png"       size="20" pos="0 40"/>
        <buttonimage id="backward"    source="minecolonies:textures/gui/down-20px.png"        size="20" pos="20 40"/>
        <buttonimage id="up"          source="minecolonies:textures/gui/plus-20px.png"        size="20" pos="40 40"/>
        <buttonimage id="confirm"     source="minecolonies:textures/gui/confirm.png"          size="32" pos="0 60"/>
        <buttonimage id="cancel"      source="minecolonies:textures/gui/cancel.png"           size="32" pos="28 60"/>
    </view>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowreplaceblock.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" pause="false"
        lightbox="true" xsi:noNamespaceSchemaLocation="file:../../../../java/com/minecolonies/blockout/blockOut.xsd">
    <label size="100% 11" pos="0 25" textalign="TOP_MIDDLE" color="white"
           label="$(com.minecolonies.coremod.gui.scan.replace.title)"/>
    <input id="name" size="150 18" pos="135 40" maxlength="25"/>

    <itemicon id="resourceIconFrom" size="17 17" pos="0 1"/>
    <label id="resourceNameFrom" size="140 12" pos="30 4" color="white"/>

    <label id="to" label="->" size="140 12" pos="170 4" color="white"/>

    <itemicon id="resourceIconTo" size="17 17" pos="210 1"/>
    <label id="resourceNameTo" size="140 12" pos="240 4" color="white"/>

    <list id="resources" size="300 120" pos="60 65">
        <box size="100% 17" linewidth="2">
            <itemicon id="resourceIcon" size="17 17" pos="1 1"/>
            <label id="resourceName" size="140 12" pos="30 1" color="white"/>
            <buttonimage label="$(com.minecolonies.coremod.gui.scanTool.select)" id="select" pos="160 1" size="86 17"
                         source="minecolonies:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
        </box>
    </list>

    <buttonimage id="done" source="minecolonies:textures/gui/buildtool/confirm.png" size="32" pos="125 185"/>
    <buttonimage id="cancel" source="minecolonies:textures/gui/buildtool/cancel.png" size="32" pos="215 185"/>
</window>

=== ldtteam/minecolonies/src/main/resources/assets/minecolonies/gui/windowhutgraveyard.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="190 244" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../../api/java/com/minecolonies/blockout/blockOut.xsd">
    <switch id="pages" size="100% 100%">
        <view id="pageActions" size="100% 100%">
            <layout source="minecolonies:gui/layouthuts/layouthutpageactions.xml"/>
        </view>
        <view id="pageGraves" size="100% 100%">
            <image source="minecolonies:textures/gui/builderhut/builder_papper.png" size="190 244"/>
            <label size="130 11" pos="30 14" color="black" textalign="MIDDLE"
                   label="$(com.minecolonies.coremod.gui.workerhuts.graveyard.graves):"/>

            <list id="graves" size="164 154" pos="13 60">
                <box size="100% 34" linewidth="2">
                    <itemicon id="icon" size="16 16" pos="1 1"/>
                    <label id="name" color="black" pos="20 2" size="130 9"/>
                    <label id="dist" color="black" pos="20 12" size="65 9"/>
                    <label id="dir" color="black" pos="20 22" size="65 9"/>
                </box>
            </list>
        </view>
    </switch>
    <buttonimage id="prevPage" size="18 10" pos="13 13" source="minecolonies:textures/gui/builderhut/turn_page_left.png"/>
    <buttonimage id="nextPage" size="18 10" pos="159 13" source="minecolonies:textures/gui/builderhut/turn_page_right.png"/>
    <label id="pageNum" size="20 11" pos="158 222" textalign="MIDDLE" label="" color="black"/>
</window>
